server:
  port: 7002
spring:
  application:
    name: Eureka-02
eureka:
  client:
    registerWithEureka: false  #不注册自己（默认true，用在集群中）
    fetchRegistry: true   #不要获取自己的信息（默认true，用在集群中）
    serviceUrl:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka