server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    url: jdbc:mysql://localhost:3306/zb_db?autoReconnect=true&useSSL=false&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

mybatis:
  # 启动xml配置
  mapperLocations: classpath:mapper/*.xml
  # 创建别名
  type-aliases-package: com.atguigu.springcloud.entities

eureka:
  client:
    #表示向注册中心注册自己 默认为true
    register-with-eureka: true
    #是否从EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #单机版：defaultZone: http://localhost:7001/eureka/ # 入驻地址
      defaultZone: http://localhost:7001/eureka ,http://localhost:7002/eureka
      #Eureka客户端向服务端发送心跳的时间间隔,默认是30s
      #lease-renewal-interval-in-seconds: 1
      #Eureka服务端在收到最后一次心跳后等待时间上限,单位为秒(默认是90s),超时将剔除服务
      #lease-expiration-duration-in-seconds: 2
  # 修改服务名，显示Ip地址
  instance:
      instance-id: payment8001
      prefer-ip-address: true
