server:
  port: 82

eureka:
  client:
    #是否从 EurekaServer抓取已有的注册信息，默认为true,单节点无所谓,集群必须设置为true才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      #单机版：defaultZone: http://localhost:7001/eureka/ # 入驻地址
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka
ribbon:
  #指的是建立连接所用时间,适用于网络状况正常情况下,两端连接所用时间
  ReadTimeout: 5000
  #指的是建立连接后从服务器读取可用资源所用时间
  ConnectTimeout: 5000

logging:
  level:
    com.guigu.springcloud.service.PaymentFeignService: debug



